# Generated by Django 5.0.1 on 2024-09-20 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='project_name',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='projects',
            name='project_techs',
            field=models.CharField(max_length=250),
        ),
    ]
